<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Monitoring SO</name>
   <tag></tag>
   <elementGuidId>57e5fe47-fd11-47a5-b576-8de5bb2a8376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[starts-with(text(),'Monitoring SO')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>Monitoring SO</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Monitoring SO' or . = 'Monitoring SO')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e224bca-8316-441a-afb1-566b7a9c9cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hP2Qbv0</value>
      <webElementGuid>f038ab51-151e-4814-b20f-9e5f70bbdc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-href z-a</value>
      <webElementGuid>3c2ca308-d7ff-4d2b-a324-295216618349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>c1594ed1-571c-48da-a482-9e4732230070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monitoring SO</value>
      <webElementGuid>155478cb-d1da-482f-91b4-393a134dc960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hP2Qbv0&quot;)</value>
      <webElementGuid>edb4ed11-6ea4-47c1-bc38-347cba4bdf37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>a4b662af-236b-4c6f-b2ea-3d3e4c882ed8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
