<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Process Complete</name>
   <tag></tag>
   <elementGuidId>e5422696-3f32-4508-ab1d-e6bc42d80b4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='hP2Qk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hP2Qk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>991eee13-03fe-4224-b0e9-541aacd701b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>baa6b26f-8f0c-4ef7-8a5c-0c780abdda41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hP2Qk</value>
      <webElementGuid>4ce6f5c3-3f01-4f07-a044-72bb6fceefb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button</value>
      <webElementGuid>ef6f7c1e-dc9b-482e-93ca-1e0c6bbd0a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Process Complete</value>
      <webElementGuid>0375466c-01c9-4c9b-9929-775aa98027cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hP2Qk&quot;)</value>
      <webElementGuid>bc267f36-4d3e-4504-8816-db0bbbcf916b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='hP2Qk']</value>
      <webElementGuid>a2cb3ced-701d-4614-9477-1d300980ee36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='hP2Qj']/button</value>
      <webElementGuid>e4c125a7-6c24-4c74-83dc-5cf8049354dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/following::button[1]</value>
      <webElementGuid>e1436852-ef3d-4674-b871-a8c6c7f842df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Data'])[1]/following::button[2]</value>
      <webElementGuid>4a243c71-4b61-4dc1-8548-f55d3618c770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/preceding::button[1]</value>
      <webElementGuid>187e2c3b-716e-4a1a-abd8-1f9b28b5885c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing_________'])[1]/preceding::button[1]</value>
      <webElementGuid>0f34e691-94a1-4ecd-88b8-f1c4db6c7fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Process Complete']/parent::*</value>
      <webElementGuid>714793ef-149a-4985-b7fa-92eeadd06a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button</value>
      <webElementGuid>bc08ee19-37e2-4074-a759-f6bc2b0e707e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'hP2Qk' and (text() = 'Process Complete' or . = 'Process Complete')]</value>
      <webElementGuid>b19ec60c-bda9-4b92-a081-f578120249ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
