<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Proses Shipment Berhasil SJPSJB12307030_a35f07</name>
   <tag></tag>
   <elementGuidId>eecb1786-7b84-4732-9406-49ca4f363bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='hP2Qox0']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.z-button-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a7265766-e328-4217-928d-3f4a46fdb26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button-image</value>
      <webElementGuid>79163fae-dea2-43b3-961e-e75c3f719c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webui/theme/BBNTheme/images/Ok24.png</value>
      <webElementGuid>2821c495-4d26-4b1e-b263-ae45b6a63bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hP2Qox0&quot;)/img[@class=&quot;z-button-image&quot;]</value>
      <webElementGuid>f650e8a2-ad79-4808-aad3-0c3bf0f3b339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='hP2Qox0']/img</value>
      <webElementGuid>088cd995-1ba4-4e7e-9836-caf610e0710f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>14072844-efa3-4c17-a4c1-2f0f2e24aaa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/webui/theme/BBNTheme/images/Ok24.png']</value>
      <webElementGuid>67ef090d-82d9-44f8-9cf8-9bee81f98b7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
