<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_hRHPz</name>
   <tag></tag>
   <elementGuidId>ee40603f-75d3-4db8-b421-e50489982e50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.login-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@type='list']//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ad7d3a0-b45b-4c0f-b7d1-777adab9f13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hRHPz</value>
      <webElementGuid>f610f4b6-2c00-415c-b4c4-1d87ae9267fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>93c4b016-1289-42b2-96d4-f55c96213e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>6de544aa-f73d-4539-be68-0fa29b19bd51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e4f7d938-f101-43b9-b08c-b39c2782d5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>37ac0d3b-0311-41b6-bf9c-116352f869f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hRHPz&quot;)</value>
      <webElementGuid>c130d1e8-31eb-47f4-b386-2ccb80e74cae</webElementGuid>
   </webElementProperties>
</WebElementEntity>
