<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SJB Bekasi_hP2Qgx0-real</name>
   <tag></tag>
   <elementGuidId>745f685a-f0bb-408a-b147-1e9ed0fadcbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hP2Qgx0-real']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hP2Qgx0-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70addc89-ec13-4e9d-ad03-c9fd01cdfd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>46a5b4a0-6994-4c5e-9403-56025732488c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hP2Qgx0-real</value>
      <webElementGuid>78c62eac-0571-4617-ac61-ed65d8c55a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hP2Qgx0-real&quot;)</value>
      <webElementGuid>b333be8d-0ee0-4eaa-baf6-070ee35d0e39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hP2Qgx0-real']</value>
      <webElementGuid>c3561372-2669-455e-988c-cd620b4adbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='hP2Qgx0']/input</value>
      <webElementGuid>e1f93bd9-7c75-43fe-b3c5-a48203da07f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/span/input</value>
      <webElementGuid>6bc8e63b-8824-4f0f-bbed-2af8eaf8310a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'hP2Qgx0-real']</value>
      <webElementGuid>e96fac01-a591-4062-baad-94b8fe51bf85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
