<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passwordFieldAdmin</name>
   <tag></tag>
   <elementGuidId>ea1ca480-8ee6-4b18-ab9f-e4531cb810b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder='Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@placeholder='Password']</value>
      <webElementGuid>f2d69c8c-8590-4928-8a4d-b9ad92124ac1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
