<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password_fa fa-fw fa-eye toggle-password</name>
   <tag></tag>
   <elementGuidId>354be1c0-b075-48ef-b323-7847671864e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw.fa-eye.toggle-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e3063cf-c35c-4071-ab11-cb43bffdc5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>toggle</name>
      <type>Main</type>
      <value>#password-field</value>
      <webElementGuid>c66baa68-c45f-4e7b-bcc2-c2ac9e07eab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-eye toggle-password</value>
      <webElementGuid>6e399950-1663-4aa7-9a44-7e3079d24e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5 col-sm-6&quot;]/div[1]/div[1]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[3]/div[@class=&quot;inner-addon left-addon&quot;]/span[@class=&quot;fa fa-fw fa-eye toggle-password&quot;]</value>
      <webElementGuid>1444b792-32d8-498e-9067-d7aa701e06ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>f3f747e6-4951-4aad-b444-965f3da024f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
