<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TEST 13 MARET 2023 EDIT FIFAPPS EDIT</name>
   <tag></tag>
   <elementGuidId>fa25d42c-7f10-4111-b200-9ae54741f53e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a20b0099232c-81']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-option-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5ddc04ef-3ccf-47be-9ba5-0dcfd103bab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option-label</value>
      <webElementGuid>8bd958b7-5003-4826-a60e-c51b8c9029a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEST 13 MARET 2023 EDIT FIFAPPS EDIT</value>
      <webElementGuid>4704d71f-6b82-4753-bddf-41cde2d800e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a20b0099232c-81&quot;)/span[@class=&quot;ng-option-label&quot;]</value>
      <webElementGuid>7ccdda9b-6cb8-4499-aafc-a59ef3aad983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a20b0099232c-81']/span</value>
      <webElementGuid>3ee40cb5-9428-4c90-8df1-61e509fa8643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Mitra'])[1]/following::span[7]</value>
      <webElementGuid>a1cc8515-e7f5-4ea3-8647-efb45f427373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distribution Task'])[1]/following::span[7]</value>
      <webElementGuid>7d84de3e-9da2-49b8-b294-6443b20d20cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Profcol to Distribute'])[1]/preceding::span[1]</value>
      <webElementGuid>5e8eedcc-d8dc-46db-9769-6cac6339db8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/preceding::span[7]</value>
      <webElementGuid>100fa98a-9223-445f-89b1-27729a489df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TEST 13 MARET 2023 EDIT FIFAPPS EDIT']/parent::*</value>
      <webElementGuid>1ca9516b-62e1-4d0e-b4cb-09e6903fbd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>7777e857-2a59-435a-ab69-f8a0743a730f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TEST 13 MARET 2023 EDIT FIFAPPS EDIT' or . = 'TEST 13 MARET 2023 EDIT FIFAPPS EDIT')]</value>
      <webElementGuid>994a3c40-b7c0-46fe-a846-c1f4ad1c8f68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
