<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_OK_z-button-image</name>
   <tag></tag>
   <elementGuidId>3c68ef62-7b94-46a0-8cda-9e516213938a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='bRUVi0']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.z-button-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cca9a895-e930-45a7-9156-e24c4943cbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button-image</value>
      <webElementGuid>c69b219e-73e8-463b-ad71-3d63d5bc75f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webui/theme/BBNTheme/images/Ok16.png;jsessionid=node01srwm68efas6q1r3f0t8tga8x015.node0</value>
      <webElementGuid>dbf1faf6-99f8-4a53-9c55-2e9d5f069c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bRUVi0&quot;)/img[@class=&quot;z-button-image&quot;]</value>
      <webElementGuid>9476324c-38c2-4cb0-9c8f-03036419ec48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='bRUVi0']/img</value>
      <webElementGuid>d9618174-1c93-46e6-b728-6174e4e5d30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>9c51d90b-b94f-42dd-a969-99ea40f6fe0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/webui/theme/BBNTheme/images/Ok16.png;jsessionid=node01srwm68efas6q1r3f0t8tga8x015.node0']</value>
      <webElementGuid>78e0d67e-0216-4f1a-ad6d-81634dbc4183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
