<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_OK_z-button-image</name>
   <tag></tag>
   <elementGuidId>653cab18-cd51-4349-81e3-cb5737e7123b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='hRHPi0']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.z-button-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>43b326e6-8f92-4294-8a60-55ada85e4c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-button-image</value>
      <webElementGuid>b18d1037-24af-45c7-96fb-d4746f13f536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webui/theme/BBNTheme/images/Ok16.png;jsessionid=node01ufqdh4idfzc1sq8zkv178alh18.node0</value>
      <webElementGuid>c8078c60-1203-4393-86bd-330422b97d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hRHPi0&quot;)/img[@class=&quot;z-button-image&quot;]</value>
      <webElementGuid>743f0af8-0303-46ce-a386-1c1b538ae48f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='hRHPi0']/img</value>
      <webElementGuid>dd6bdfcc-62dd-4ff3-b178-06ef73d5b97a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>a585c600-0b2e-4c11-a6e1-d8fb7db8601d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/webui/theme/BBNTheme/images/Ok16.png;jsessionid=node01ufqdh4idfzc1sq8zkv178alh18.node0']</value>
      <webElementGuid>76c55325-c91d-4902-b37f-f9965d0f6c62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
