<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_hRHPz</name>
   <tag></tag>
   <elementGuidId>3fc8915e-3bbc-408f-b651-83837d1d4d78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@autocomplete='current-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.login-field</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@autocomplete = 'current-password' and @type = 'password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba5c6765-4822-4454-a884-e723ad17cb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hRHPz</value>
      <webElementGuid>bf9ed22b-06cb-4f8a-9018-7cf972312705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-textbox</value>
      <webElementGuid>64c1c135-4615-4245-8ea1-35a76fadaa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>2b06e2f4-2c6a-493f-b032-71ce98912062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e54ca793-87d9-4ae3-8b02-aaeb2acdd57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>71ef8223-c272-4c5b-a204-6939230cb9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hRHPz&quot;)</value>
      <webElementGuid>28d255d9-a4b6-4e95-8ec0-83b071dcc103</webElementGuid>
   </webElementProperties>
</WebElementEntity>
